hackershack_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="accounts"
urlpatterns = [  
    path("profile", views.ProfileView.as_view(), name="profile"),
    #Django auth
    path('login',
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login"),

    path('logout', auth_views.LogoutView.as_view(), name="logout"), 

]

hackershack_website/apps/contact/urls.py
from django.urls import path
from .views import contact

app_name = "contact"

urlpatterns = [
    path("", contact, name="contact"), 
    ]

hackershack_website/urls.py
from re import template
from django.contrib import admin
from django.contrib import auth
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # module path to be included 
    path("", include('hackershack_website.apps.public.urls') ),
    path("accounts/", include('hackershack_website.apps.accounts.urls')),
    path("contact/", include('hackershack_website.apps.contact.urls')),


]

hackershack_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http import request


class UserInterest(models.Model):
    name = models.CharField(max_length=64,unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class UserPersona(models.Model):
    name = models.CharField(max_length=64,unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# Create your models here.

#request.user.profile

class UserProfile(models.Model):
    #foreign key (owner)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    #settings
    is_full_name_displayed = models.BooleanField(default=True)
    #details
    bio = models.CharField(max_length=500,blank=True,null=True)
    website = models.URLField(max_length=200,blank=True,null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    #many profiles asociated with many interest
    interest = models.ManyToManyField(UserInterest, blank=True)

hackershack_website/apps/contact/models.py
from django.db import models

# Create your models here.

hackershack_website/apps/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Name"} ))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'form-control','placeholder':"Email"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class':'form-control','placeholder':"Message",'rows':5}))

hackershack_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin



# the order of the inheritance of classes mathers
# if i switch LoginRequiredMixin, TemplateView to :  TemplateView, LoginRequiredMixin the auth features of LoginRequiredMixin are lost
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

hackershack_website/apps/contact/views.py
from django import forms
from django.forms.widgets import EmailInput
from django.shortcuts import render
from .forms import ContactForm
from django.core.mail import send_mail
from hackershack_website import settings
import bleach
def contact(request):

    if request.method  == "GET" :
        form = ContactForm()

    elif  request.method  == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            #bleach is for cleaning the data in order counter measure for attacks
            name =  bleach.clean(form.cleaned_data["name"])
            email = bleach.clean(form.cleaned_data["email"])
            message = bleach.clean(form.cleaned_data["message"])
            send_mail( f"{name} sent an email", message,email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form":form, "success":True} )

    else:
        raise NotImplementedError
    return render(request, "contact.html", {"form":form})

hackershack_website/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin



# the order of the inheritance of classes mathers
# if i switch LoginRequiredMixin, TemplateView to :  TemplateView, LoginRequiredMixin the auth features of LoginRequiredMixin are lost
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

hackershack_website/templates/about.html
{% extends 'base.html' %}


{% block title %} About {% endblock %}


{% block content %}

<h2> si que si estas en la pagina de about :)</h2>
{% endblock %}

hackershack_website/templates/accounts/login.html
{% extends 'base.html' %}


{% block title %} Login {% endblock %}


{% block content %}

<h2> ostras tio que este es un login page</h2>
<form method="POST">
    <!-- CSRF TOKEN-->
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

hackershack_website/templates/accounts/profile.html
{% extends 'base.html' %}


{% block title %} Profile {% endblock %}


{% block content %}

<h1> {{user.get_full_name}} (@{{ user.username }}) </h1>

    {% with profile=user.profile %}
        {% if profile %}
        <h2>
            {{profile.persona|default:""}}
        </h2>
        <div>
            {{ profile.bio|default:"" }}
        </div>

        <div>
            {% with website=profile.website|default:"" %}
            <a href="{{website}}">{{website}}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interest:
            {% for interest in profile.interest.all %} <!-- query to db -->
            <span> {{interest.name}}{% if not forloop.last %}, {% endif %} </span>    
            {% endfor %}
        </div>
        {% endif %} <!-- end if profile-->
    {% endwith %} <!-- with caches a complex variable under a simpler name. This is useful when accessing an “expensive” method (e.g., one that hits the database) multiple times.-->

{% endblock %}

hackershack_website/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} Hacker Shack {% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %} " rel="stylesheet" />
    <link href="{% static 'css/main.css' %} " rel="stylesheet" />

</head>
<body>
    {% include 'navbar.html' %}
    <main id="main">
    {% block content %}

    {% endblock %}

    </main>

       <!-- Bootstrap core JS-->
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
       <!-- Core theme JS-->
       <script src="{% static 'theme/js/scripts.js' %} "></script>
       <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
       <!-- * *                               SB Forms JS                               * *-->
       <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
       <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
       <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

hackershack_website/templates/contact.html
{% extends 'base.html' %}


{% block title %} Contact {% endblock %}


{% block content %}

<section class="page-section" 1d="contact">
<div class= "container">
<!-- Contact Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"> Contact Us </h2>
<!-- Icon Divider -->
<div class="divider-custom"> 
<div class="divider-custom-line"> </div>
<div class="divider-custom-icon"><i class="fas fa-envelope"> </i> </div>
<div class="divider-custom-line"> </div>
</div>
<div class= text-center text-secondary mb-0>
<p>
     We do our best to respond to emails, but we get so many that it's sometimes hard to respond to all of them. If you don't
</p>
<p> 
    If you need help with a coding project, please don't send us an email. We don't have enough bandwidth to answer specific
</p>
 <p>  
     You con also send us an email at <a href="mailto:juan@rubisco.mx"> juan@rubisco.mx</a>
</p> 
</div>

<!-- Contact Section Form-->
<div class="row">
    <div class=" col-lg-8 mx-auto">
        {% if success %}
        <div class="alert alert-success" role="alert">
            your message was sent! check your inbox for a response.
          </div>
        {% endif %}
        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on 1-->
        <form id="contactForm" name="sentMessage" novalidate="novalidate", method="post">
            {% csrf_token %}

            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{form.non_field_errors}}
              </div>
            {%endif %}
            {% for field in form %}
                <div class="control-group">
                    <div class=" form-group floating-label-form-group controls mb-0 pb-2">
                        {{ field.label_tag }}
                        {{ field }}
                        {% for error in field.errors %}
                        <p class="help-black text-danger"> {{error}}</p>
                        {% endfor %}
                    </div>  
                </div>
            {% endfor %}
          

           <br/>     
            <div class="form-group"> <button class="btn sczen-bg-primary btn-xl text-white" id="sendMessageButton" type="submit"> Send</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

hackershack_website/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}


{% block content %}
<!--"C:\Users\eider\Documents\GitHub\django hacker shack\static\theme\assets\img\avataaars.svg"-->
<!-- static/theme/assets/img/avataaars.svg-->
<!-- {% static 'theme/assets/img/avataaars.svg' %} -->

 <!-- Masthead-->
 <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'img/walle-circle.png' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Lorem ipsum dolor</h1>
       
    </div>
</header>
{% endblock %}

hackershack_website/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}


   <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{index_url}}">Sciudatazen</a>
        <button class="navbar-toggler text-uppercase font-weight-bold sczen-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3   {% if request.path == index_url %} active{% endif%}" href="{{index_url}}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3  {% if request.path == about_url %}active{% endif%}" href="{{about_url}}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3  {% if request.path == contact_url %} active{% endif%}" href="{{contact_url}}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>



<!-- old navbar-->
{% comment "old navbar" %}
    <nav>
        {% url 'public:index' as index_url %}
        <!-- el nombre de 'index' hace match con el arg name en el path en urls.py-->
        <span>
            {% if request.path == index_url %} Home 
            {% else %}<a href="{{index_url}}">Home</a>{% endif %}
        </span> 

        {% url 'public:about' as about_url %}
        <span>
            {% if request.path == about_url %} About
            {% else %} <a href="{{about_url}}">About</a> {% endif %}
            </span>

        {% url 'contact:contact' as contact_url %}
        <span>
            {% if request.path == contact_url %} Contact
            {% else %} <a href="{{contact_url}}">Contact</a> {% endif %}
            </span>

                <!--User profile menu -->
            <span style="float:right;">
                {% if user.is_authenticated %}

                {% url 'accounts:profile' as profile_url %}
            
                <span> Hi {% if request.path == profile_url %} {{user.username}} :)
                    {% else %} <a href="{{profile_url}}">{{user.username}} </a> 
                    {%endif%}
                </span>

                <span> <a href="{% url 'accounts:logout' %}">Logout </a> </span>
                {% else %}
                <span> <a href="{% url 'accounts:login' %}">Login </a> </span>
                {% endif %}
            </span>
    </nav>  -->
{% endcomment  %}